version: "3"
services:
  wordpress:
    image: wordpress
    ports:
      - "8080:80"
    environment:
      - WORDPRESS_DB_PASSWORD=temp
      - SHELL=/bin/bash
    volumes:
      - ./app:/var/www/html

  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=temp
